service: smart-home-device-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2
  region: us-east-1
  memorySize: 128
  timeout: 10
  environment:
    DEVICES_TABLE: DevicesTable
    DEVICE_QUEUE_URL:
      Ref: DeviceQueue

package:
  individually: true
  exclude:
    - "**"

functions:
  create:
    handler: bootstrap
    package:
      artifact: build/create.zip
    role: CreateFunctionRole

  get:
    handler: bootstrap
    package:
      artifact: build/get.zip
    role: GetFunctionRole

  update:
    handler: bootstrap
    package:
      artifact: build/update.zip
    role: UpdateFunctionRole

  delete:
    handler: bootstrap
    package:
      artifact: build/delete.zip
    role: DeleteFunctionRole

  sqs:
    handler: bootstrap
    package:
      artifact: build/sqs.zip
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - DeviceQueue
              - Arn
    role: SQSFunctionRole

resources:
  Resources:
    DevicesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: DevicesTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    DeviceQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: DeviceAssociationQueue

    CreateFunctionRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: create-function-role
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: CreateDevicePolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:PutItem
                  Resource:
                    Fn::GetAtt: [DevicesTable, Arn]
                - ${file(./serverless.iam.logs.yml):LogAccess}

    GetFunctionRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: get-function-role
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: GetDevicePolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:GetItem
                  Resource:
                    Fn::GetAtt: [DevicesTable, Arn]
                - ${file(./serverless.iam.logs.yml):LogAccess}

    UpdateFunctionRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: update-function-role
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: UpdateDevicePolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:UpdateItem
                  Resource:
                    Fn::GetAtt: [DevicesTable, Arn]
                - ${file(./serverless.iam.logs.yml):LogAccess}

    DeleteFunctionRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: delete-function-role
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: DeleteDevicePolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:DeleteItem
                  Resource:
                    Fn::GetAtt: [DevicesTable, Arn]
                - ${file(./serverless.iam.logs.yml):LogAccess}

    SQSFunctionRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: sqs-function-role
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: SQSPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:UpdateItem
                  Resource:
                    Fn::GetAtt: [DevicesTable, Arn]
                - Effect: Allow
                  Action:
                    - sqs:ReceiveMessage
                    - sqs:DeleteMessage
                    - sqs:GetQueueAttributes
                  Resource:
                    Fn::GetAtt: [DeviceQueue, Arn]
                - ${file(./serverless.iam.logs.yml):LogAccess}
